<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5IC372P" name="Test(failed)" tests="2" failures="2" timestamp="30 Mar 2017 12:46:38 GMT" time="0.034" errors="0">
  <testcase name="show5" time="0.012" classname="com.selenium.testNG.Testng5">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.selenium.testNG.Testng5.show5(Testng5.java:16)
	at com.selenium.testNG.TestrunnerForRerunFailedTestcasesAutomatically.main(TestrunnerForRerunFailedTestcasesAutomatically.java:17)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- show5 -->
  <testcase name="show2" time="0.0" classname="com.selenium.testNG.Testng2">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at com.selenium.testNG.Testng2.show2(Testng2.java:13)
	at com.selenium.testNG.TestrunnerForRerunFailedTestcasesAutomatically.main(TestrunnerForRerunFailedTestcasesAutomatically.java:17)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- show2 -->
</testsuite> <!-- Test(failed) -->
